version: '3'
services:
  nginx:
    build: ./nginx
    ports:
        - "80:80"
    volumes:
        - /Users/michael/Documents/Code/portfolio/nginx:/nginx
  backend:
    build: ./backend
    ports:
        - "5000:5000"
    volumes:
        - /Users/michael/Documents/Code/portfolio/backend:/backend
  frontend:
    stdin_open: true
    build: ./frontend
    ports:
        - "3000:3000"
    volumes:
        - /Users/michael/Documents/Code/portfolio/frontend:/frontend