version: '3'
services:
  nginx:
    build: ./nginx
    ports:
        - "80:80"
    volumes:
        - /${NGINX_VOLUME}:/nginx
    environment:
        - FE_DOMAIN
        - BE_DOMAIN
    depends_on:
        - frontend
        - backend
  backend:
    build: ./backend
    ports:
        - "5000:5000"
    volumes:
        - /${BACKEND_VOLUME}:/backend
    environment:
        - EMAIL_ADDRESS
        - EMAIL_USER
        - EMAIL_PASSWORD
        - ENVIRONMENT_TYPE
  frontend:
    stdin_open: true
    build: ./frontend
    ports:
        - "3000:3000"
    volumes:
        - /${FRONTEND_VOLUME}:/frontend
        - /frontend/node_modules
    environment:
        - ENVIRONMENT_TYPE